name: CI

on: [push, pull_request]

jobs:
  lint:
    name: Pylint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Prepare
        run: |
          pip install poetry pylint
          poetry install
      - name: Run pylint
        run: pylint wallger
